const fmt=n=>Number(n).toLocaleString('en-US');
const state={page:'board',market:'US',skuQ:'',health:'all',ageQ:'',inQ:'',lotQ:'',group:'all',site:'all',period:'month',metric:'qty'};
const board={
US:{label:'美国',sku:229,sellable:34895,producing:167983,transit:137553,actual:57360,dos:43.6,stockout:91,oneWh:24,tight:49,aged:15,agedPct:'5.0%',months:[{m:'9月在途',n:6304,h:17,muted:true},{m:'10月在途',n:27033,h:73,muted:true},{m:'11月预计',n:37054,h:100,muted:false},{m:'12月预计',n:33635,h:91,muted:false},{m:'1月预计',n:33536,h:90,muted:false}],warehouses:[['美东',24182,1598,10128,13538,11773,11502],['美西',5588,2062,5047,8154,7823,7832],['美东南',15152,2197,6520,8207,7776,7845],['美南',12438,447,5338,7155,6263,6357]]},
EU:{label:'欧洲',sku:86,sellable:12440,producing:41820,transit:29610,actual:14880,dos:38.2,stockout:19,oneWh:11,tight:17,aged:6,agedPct:'4.1%',months:[{m:'9月在途',n:2140,h:22,muted:true},{m:'10月在途',n:6120,h:62,muted:true},{m:'11月预计',n:9840,h:100,muted:false},{m:'12月预计',n:7210,h:73,muted:false},{m:'1月预计',n:4300,h:44,muted:false}],warehouses:[['亚马逊',9720,1420,3980,6120,4510,2680],['多平台',5160,720,2140,3720,2700,1620]]}
};
const skus=[['B01PF-002BMJ','记忆棉床垫 10cm','床垫',4200,1860,920,0,12.4,0,'无库存',0,'缺货'],['B01PF-008QSL','乳胶枕标准款','枕芯',1800,640,310,210,8.2,25.6,'健康',2,'2仓'],['B07KX-114NVA','防水床笠 180x200','床品',960,2200,1400,880,18.6,47.3,'偏多',4,'健康'],['B09AM-331CTS','冷却凝胶床垫 25cm','床垫',6200,4100,1980,126,21,6,'紧缺',1,'1仓'],['B11QT-019HSE','酒店款枕头双只装','枕芯',0,0,0,0,0,0,'无库存',0,'缺货'],['B03LW-220DKP','针织床笠灰','床品',740,380,210,1560,22,70.9,'积压',5,'健康'],['B15ZX-088RMB','儿童床垫 120x200','床垫',2100,980,540,410,9.8,41.8,'健康',3,'健康'],['B18YH-056PLW','可水洗夏被','被芯',350,120,80,92,3.4,27.1,'健康',2,'2仓'],['B20CK-401FBA','床架排骨架','家具',0,760,400,0,0,0,'无库存',0,'缺货'],['B22MN-017GHT','记忆枕低款','枕芯',1280,540,260,1880,14.2,132.4,'积压',6,'健康'],['B25TR-903AEU','欧洲尺寸床笠','床品',410,190,90,240,6.1,39.3,'健康',1,'覆盖不足'],['B28UD-112OSP','护脊床垫 20cm','床垫',5100,2600,1310,0,1.8,0,'无库存',0,'缺货']];
const aged=[['B22MN-017GHT','记忆枕低款',940,1880,'50.0%','高'],['B03LW-220DKP','针织床笠灰',510,1560,'32.7%','中'],['B07KX-114NVA','防水床笠 180x200',160,880,'18.2%','中'],['B18YH-056PLW','可水洗夏被',28,92,'30.4%','中'],['B15ZX-088RMB','儿童床垫 120x200',62,410,'15.1%','低'],['B01PF-008QSL','乳胶枕标准款',18,210,'8.6%','低']];
const inbound=[['B01PF-002BMJ','记忆棉床垫 10cm','床垫',2400,340,220.9,6,1860],['B09AM-331CTS','冷却凝胶床垫 25cm','床垫',1800,126,91.9,4,4100],['B28UD-112OSP','护脊床垫 20cm','床垫',1600,78,93.2,3,2600],['B15ZX-088RMB','儿童床垫 120x200','床垫',720,410,115.5,2,980],['B01PF-008QSL','乳胶枕标准款','枕芯',480,210,84.1,3,640],['B25TR-903AEU','欧洲尺寸床笠','床品',300,240,88.5,2,190]];
const lots=[['2026-09-12','2026-09','B01PF-002BMJ','记忆棉床垫 10cm','MSNJ01','已签收',800,'实际送仓','A-1902','TCLU88321',12],['2026-09-18','2026-09','B09AM-331CTS','冷却凝胶床垫 25cm','LA10','已签收',420,'实际送仓','A-2044','TCLU77109',0],['2026-09-22','2026-10','B28UD-112OSP','护脊床垫 20cm','ATL02','在途',600,'发货数量','B-1180','TCLU66012','—'],['2026-10-03','2026-10','B01PF-008QSL','乳胶枕标准款','HOU04','已离港',240,'发货数量','B-2219','TCLU55930','—'],['2026-10-08','2026-10','B15ZX-088RMB','儿童床垫 120x200','MSNJ02','清关中',360,'发货数量','C-0771','TCLU44881','—'],['2026-08-16','2026-08','B03LW-220DKP','针织床笠灰','XHLAX1A','已签收',180,'实际送仓','A-0888','TCLU33210',6],['2026-11-02','2026-11','B07KX-114NVA','防水床笠 180x200','XHNJ02','计划',500,'预计送仓','—','—','—']];
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.style.display='block';clearTimeout(toast._t);toast._t=setTimeout(()=>el.style.display='none',1600);}
function healthTag(h){const map={'紧缺':'bad','无库存':'bad','缺货':'bad','偏多':'mid','积压':'warn','健康':'ok','1仓':'warn','2仓':'warn','覆盖不足':'warn'};return `<span class="tag ${map[h]||'mute'}">${h}</span>`;}
function riskTag(r){const map={'高':'bad','中':'warn','低':'ok'};return `<span class="tag ${map[r]||'mute'}">${r}</span>`;}
function whDots(n){let s='';for(let i=0;i<7;i++)s+=`<i class="${i<n?(n>=3?'on':n===2?'low':'off'):''}"></i>`;return `<span class="wh" title="有货仓 ${n}/7">${s}</span>`;}
function marketSeg(){return `<div class="seg"><button type="button" class="${state.market==='US'?'on':''}" data-market="US">美国</button><button type="button" class="${state.market==='EU'?'on':''}" data-market="EU">欧洲</button></div>`;}
function renderBoard(){const d=board[state.market];const sums=Array(d.warehouses[0].length-1).fill(0);d.warehouses.forEach(r=>r.slice(1).forEach((v,i)=>sums[i]+=v));const vs=Math.min(100,d.sellable/d.transit*100);
document.getElementById('page-board').innerHTML=`<div class="page-head"><h2>库存看板 <span>/ ${d.label}</span></h2>${marketSeg()}</div>
<div class="row-label">库存体量 · ${d.sku} 个 SKU</div>
<section class="kpis volume">
<article class="kpi hero"><div class="label">海外可售</div><div class="val">${fmt(d.sellable)}</div><div class="hint">件 · 可售 / 在途 ${(d.sellable/d.transit*100).toFixed(1)}%</div><div class="mix"><b style="width:${vs}%"></b><i style="width:${100-vs}%"></i></div></article>
<article class="kpi"><div class="label">在产</div><div class="val">${fmt(d.producing)}</div><div class="hint">件</div></article>
<article class="kpi"><div class="label">合计在途</div><div class="val">${fmt(d.transit)}</div><div class="hint">件 · 实际在途 ${fmt(d.actual)}</div></article>
<article class="kpi"><div class="label">平均可售天数</div><div class="val">${d.dos}</div><div class="hint">天 · 健康档 25-45</div></article></section>
<div class="row-label">风险 · 占比相对当前市场 ${d.sku} SKU</div>
<section class="kpis risk">
<article class="kpi bad"><div class="label">缺货 · 0 仓</div><div class="val">${d.stockout}</div><div class="hint">${d.stockout} / ${d.sku} · ${(d.stockout/d.sku*100).toFixed(1)}%</div></article>
<article class="kpi warn"><div class="label">${state.market==='US'?'仅 1 仓':'覆盖不足'}</div><div class="val">${d.oneWh}</div><div class="hint">${d.oneWh} / ${d.sku} · ${(d.oneWh/d.sku*100).toFixed(1)}%</div></article>
<article class="kpi warn"><div class="label">可售紧缺</div><div class="val">${d.tight}</div><div class="hint">${d.tight} / ${d.sku} · ${(d.tight/d.sku*100).toFixed(1)}% · ≤25 天</div></article>
<article class="kpi info"><div class="label">高库龄</div><div class="val">${d.aged}</div><div class="hint">${d.aged} / ${d.sku} · ${d.agedPct} >180 天</div></article></section>
<section class="split"><div class="panel"><div class="panel-h"><h3>在途 · 按月</h3><p>实际在途与各分月在途为源表并列口径，不可相互加总。</p><div class="meta">${d.label} · 分月到仓 ${fmt(d.transit)} 件 · 实际在途 ${fmt(d.actual)} 件</div></div>
<div class="bars">${d.months.map(x=>`<div class="bar"><div class="n mono">${fmt(x.n)}</div><div class="col"><div class="fill ${x.muted?'muted':''}" style="height:${x.h}%"></div></div><div class="m">${x.m}</div></div>`).join('')}</div></div>
<div class="panel"><div class="panel-h"><h3>在途 · ${state.market==='US'?'分仓按月':'分渠道按月'}</h3><p>${state.market==='US'?'仅美国四区按月披露。':'欧洲源表按亚马逊 / 多平台两桶，不是地理仓。'}</p><div class="meta">单位：件</div></div>
<div class="table-wrap"><table><thead><tr><th class="l">${state.market==='US'?'仓库':'渠道'}</th><th>实际在途</th><th>9月</th><th>10月</th><th>11月预计</th><th>12月预计</th><th>1月预计</th></tr></thead><tbody>${d.warehouses.map(r=>`<tr><td class="l">${r[0]}</td>${r.slice(1).map(v=>`<td class="n">${fmt(v)}</td>`).join('')}</tr>`).join('')}</tbody><tfoot><tr><td class="l">合计</td>${sums.map(v=>`<td class="n">${fmt(v)}</td>`).join('')}</tr></tfoot></table></div></div></section>
<div class="foot"><span>市场口径 ${d.label} · 海外可售 ${fmt(d.sellable)} · 合计在途 ${fmt(d.transit)}</span><span>看板高库龄与侧栏 29 为不同源，不可加总</span></div>`;}
function renderSku(){const q=state.skuQ.trim().toLowerCase();const rows=skus.filter(r=>(!q||r[0].toLowerCase().includes(q)||r[1].includes(q)||r[2].includes(q))&&(state.health==='all'||r[9]===state.health));
document.getElementById('page-sku').innerHTML=`<div class="page-head"><h2>SKU 库存明细 <span>/ ${board[state.market].label}</span></h2><div class="tools">${marketSeg()}<input class="search" id="skuSearch" placeholder="搜索 SKU / 名称 / 类目" value="${state.skuQ}"/><select class="filt" id="skuHealth"><option value="all">全部健康度</option>${['紧缺','健康','偏多','积压','无库存'].map(x=>`<option ${state.health===x?'selected':''}>${x}</option>`).join('')}</select></div></div><p class="row-label">样例 ${rows.length} 行 · 不能核对看板 229</p><div class="panel table-wrap"><table><thead><tr><th class="l">SKU</th><th class="l">产品名称</th><th class="l">类目</th><th>在产</th><th>合计在途</th><th>实际在途</th><th>可售</th><th>日销</th><th>可售天数</th><th class="l">健康度</th><th class="l">库存分布</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="l mono">${r[0]}</td><td class="l">${r[1]}</td><td class="l">${r[2]}</td><td class="n">${fmt(r[3])}</td><td class="n">${fmt(r[4])}</td><td class="n">${fmt(r[5])}</td><td class="n">${fmt(r[6])}</td><td class="n">${r[7]}</td><td class="n">${r[8]}</td><td class="l">${healthTag(r[9])}</td><td class="l">${whDots(r[10])} ${healthTag(r[11])}</td></tr>`).join('')||'<tr><td class="l" colspan="11">没有匹配的 SKU</td></tr>'}</tbody></table></div>`;
const s=document.getElementById('skuSearch');const h=document.getElementById('skuHealth');if(s)s.oninput=e=>{state.skuQ=e.target.value;renderSku();s.focus();s.setSelectionRange(s.value.length,s.value.length);};if(h)h.onchange=e=>{state.health=e.target.value;renderSku();};}
function renderAge(){const q=state.ageQ.trim().toLowerCase();const rows=aged.filter(r=>!q||r[0].toLowerCase().includes(q)||r[1].includes(q));
document.getElementById('page-age').innerHTML=`<div class="page-head"><h2>高库龄预警</h2><div class="tools"><input class="search" id="ageSearch" placeholder="搜索 SKU / 名称" value="${state.ageQ}"/></div></div><section class="kpis three"><article class="kpi"><div class="label">库龄表 SKU</div><div class="val">29</div><div class="hint">侧栏计数 · 库龄表口径</div></article><article class="kpi warn"><div class="label">目标</div><div class="val">>180 ≤5%</div><div class="hint">>120 天占比 ≤ 15%</div></article><article class="kpi bad"><div class="label">高风险示例</div><div class="val">1</div><div class="hint">本页样例 6 行</div></article></section><div class="panel table-wrap"><table><thead><tr><th class="l">SKU</th><th class="l">产品名称</th><th>>180天可售</th><th>整体可售</th><th>>180天占比</th><th class="l">风险等级</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="l mono">${r[0]}</td><td class="l">${r[1]}</td><td class="n">${fmt(r[2])}</td><td class="n">${fmt(r[3])}</td><td class="n">${r[4]}</td><td class="l">${riskTag(r[5])}</td></tr>`).join('')}</tbody></table></div>`;
const s=document.getElementById('ageSearch');if(s)s.oninput=e=>{state.ageQ=e.target.value;renderAge();s.focus();s.setSelectionRange(s.value.length,s.value.length);};}
function renderInbound(){const q=state.inQ.trim().toLowerCase();const rows=inbound.filter(r=>!q||r[0].toLowerCase().includes(q)||r[1].includes(q));
document.getElementById('page-inbound').innerHTML=`<div class="page-head"><h2>SKU 到货看板 <span>/ ${board[state.market].label}</span></h2><div class="tools">${marketSeg()}<input class="search" id="inSearch" placeholder="搜索 SKU / 名称" value="${state.inQ}"/></div></div><p class="row-label">到仓日期 ≤20 日计入当月，21 日起计入次月</p><div class="panel table-wrap"><table><thead><tr><th class="l">SKU</th><th class="l">产品名称</th><th class="l">类目</th><th>合计到货</th><th>现有可售</th><th>到货后可售天数</th><th>到货批次</th><th>汇总在途</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="l mono">${r[0]}</td><td class="l">${r[1]}</td><td class="l">${r[2]}</td><td class="n">${fmt(r[3])}</td><td class="n">${fmt(r[4])}</td><td class="n">${r[5]}</td><td class="n">${r[6]}</td><td class="n">${fmt(r[7])}</td></tr>`).join('')}</tbody></table></div>`;
const s=document.getElementById('inSearch');if(s)s.oninput=e=>{state.inQ=e.target.value;renderInbound();s.focus();s.setSelectionRange(s.value.length,s.value.length);};}
function renderLots(){const q=state.lotQ.trim().toLowerCase();const rows=lots.filter(r=>!q||r.join(' ').toLowerCase().includes(q));
document.getElementById('page-lots').innerHTML=`<div class="page-head"><h2>到货批次明细</h2><div class="tools"><input class="search" id="lotSearch" placeholder="搜索 SKU / 仓 / 柜号" value="${state.lotQ}"/></div></div><p class="row-label">样例 ${rows.length} / 源表 2,995</p><div class="panel table-wrap"><table><thead><tr><th>到仓日期</th><th>归属月</th><th class="l">SKU</th><th class="l">产品名称</th><th class="l">目的仓</th><th class="l">物流状态</th><th>到货数量</th><th class="l">口径</th><th class="l">箱号</th><th class="l">货柜号</th><th>差异</th></tr></thead><tbody>${rows.map(r=>`<tr><td class="n">${r[0]}</td><td class="n">${r[1]}</td><td class="l mono">${r[2]}</td><td class="l">${r[3]}</td><td class="l">${r[4]}</td><td class="l">${r[5]}</td><td class="n">${fmt(r[6])}</td><td class="l">${r[7]}</td><td class="l">${r[8]}</td><td class="l">${r[9]}</td><td class="n">${r[10]}</td></tr>`).join('')}</tbody></table></div>`;
const s=document.getElementById('lotSearch');if(s)s.oninput=e=>{state.lotQ=e.target.value;renderLots();s.focus();s.setSelectionRange(s.value.length,s.value.length);};}
function renderSales(){const cells=[['洛阳组 · 美国',4280,186420,41280],['洛阳组 · 欧洲',1190,62410,10880],['深圳组 · 美国',3610,154900,33620],['深圳组 · 加拿大',640,28100,4920]];
const metric=state.metric;
document.getElementById('page-sales').innerHTML=`<div class="page-head"><h2>目标完成 / 日报</h2><div class="tools"><div class="seg">${[['all','全部组'],['ly','洛阳组'],['sz','深圳组']].map(([v,l])=>`<button type="button" class="${state.group===v?'on':''}" data-group="${v}">${l}</button>`).join('')}</div><div class="seg">${[['all','全部站点'],['us','美国'],['ca','加拿大'],['eu','欧洲']].map(([v,l])=>`<button type="button" class="${state.site===v?'on':''}" data-site="${v}">${l}</button>`).join('')}</div><div class="seg">${[['7d','近7天'],['month','本月']].map(([v,l])=>`<button type="button" class="${state.period===v?'on':''}" data-period="${v}">${l}</button>`).join('')}</div><div class="seg">${[['qty','件数'],['gmv','销售额'],['profit','利润预估']].map(([v,l])=>`<button type="button" class="${state.metric===v?'on':''}" data-metric="${v}">${l}</button>`).join('')}</div></div></div><p class="row-label">销售额含买家运费 · 格子为样例</p><div class="sales-grid">${cells.map(c=>{const val=metric==='qty'?c[1]:metric==='gmv'?c[2]:c[3];return `<article class="cell"><div class="k">${c[0]}</div><div class="v mono">${fmt(val)}</div><div class="k">${metric==='qty'?'件':'USD'} · ${state.period==='7d'?'近7天':'本月'}</div></article>`;}).join('')}</div>`;}
function renderHelp(){document.getElementById('page-help').innerHTML=`<div class="page-head"><h2>帮助 · 口径</h2></div><div class="help"><h3>怎么读各页</h3><ul><li>库存看板：市场级汇总，不随明细筛选变化。</li><li>SKU 库存明细：逐行明细，筛选只影响本页。</li><li>高库龄预警：库龄表口径，按超 180 天占比。</li><li>到货看板 / 批次：20 号规则归月。</li></ul><p>三类数字基准日不同，不可交叉相加。美国看板数字来自 2026-09-18 现网快照。</p></div>`;}
const renderers={board:renderBoard,sku:renderSku,age:renderAge,inbound:renderInbound,lots:renderLots,sales:renderSales,help:renderHelp};
function showPage(id){if(!renderers[id])id='board';state.page=id;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('on',p.id==='page-'+id));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===id));if(location.hash!=='#'+id)location.hash=id;renderers[id]();}
window.addEventListener('hashchange',()=>{const id=(location.hash||'#board').replace('#','')||'board';if(id!==state.page)showPage(id);});
document.querySelector('.sidebar').addEventListener('click',e=>{const btn=e.target.closest('.nav-item');if(btn)showPage(btn.dataset.page);});
document.addEventListener('click',e=>{const m=e.target.closest('[data-market]');if(m){state.market=m.dataset.market;renderers[state.page]();}const g=e.target.closest('[data-group]');if(g){state.group=g.dataset.group;renderSales();}const s=e.target.closest('[data-site]');if(s){state.site=s.dataset.site;renderSales();}const p=e.target.closest('[data-period]');if(p){state.period=p.dataset.period;renderSales();}const met=e.target.closest('[data-metric]');if(met){state.metric=met.dataset.metric;renderSales();}if(e.target.id==='btnRefresh')toast('已按当前基准刷新（原型）');if(e.target.id==='btnExport')toast('已导出当前表（原型）');});
showPage((location.hash||'#board').replace('#','')||'board');
